var hydroclimStyles = [
    { name: "Temp and Flow", value: "hydroclim:temp_flow_5_degree" },
    { name: "Temp and Flow Lowest", value: "hydroclim:temp_and_flow_low" },
    { name: "Temp and Flow Highest", value: "hydroclim:temp_and_flow_high" },
    { name: "Temperature", value: "hydroclim:temperature" },
    { name: "Flow", value: "hydroclim:flow_only" },
    { name: "Flow Lowest", value: "hydroclim:flow_only_low" },
    { name: "Flow Highest", value: "hydroclim:flow_only_high" }
];

var months = [{ name: "January", value: 1 }, { name: "February", value: 2 }, { name: "March", value: 3 }, { name: "April", value: 4 }, { name: "May", value: 5 }, { name: "June", value: 6 }, { name: "July", value: 7 }, { name: "August", value: 8 }, { name: "September", value: 9 }, { name: "October", value: 10 }, { name: "November", value: 11 }, { name: "December", value: 12 }];
var seasons = [{ name: "Spring", value: 'spring' }, { name: "Summer", value: 'summer' }, { name: "Autumn", value: 'autumn' }, { name: "Winter", value: 'winter' }];

var modelsList45 = [
    { name: 'access1-0.1', id: 1, description: 'Commonwealth Scientific and Industrial Research Organization and Bureau of Meterology,Australia', country: 'Australia' },
    { name: 'bcc-csm1-1.1', id: 2, description: 'Beijing Climate Center,China Meteorological Administration', country: 'China' },
    { name: 'canesm2.1', id: 3, description: 'Canadian Centre for Climate Modelling and Analysis', country: 'Canada' },
    { name: 'ccsm4.1', id: 4, description: 'National Center for Atmospheric Research', country: 'USA' },
    { name: 'cesm1-bgc.1', id: 5, description: 'Community Earth System Model Contributors', country: 'USA' },
    { name: 'cnrm-cm5.1', id: 6, description: 'Centre National de Recherches M�t�orologiques/Centre Europ�en de Recherche et Formation Avanc�e en Calcul Scientifique', country: 'France' },
    { name: 'csiro-mk3-6-0.1', id: 7, description: 'Commonwealth Scientific and Industrial Research Organization,Queensland Climate Change Centre of Excellence', country: 'Australia' },
    { name: 'gfdl-esm2g.1', id: 8, description: 'NOAA Geophysical Fluid Dynamics Laboratory', country: 'USA' },
    { name: 'gfdl-esm2m.1', id: 9, description: 'NOAA Geophysical Fluid Dynamics Laboratory', country: 'USA' },
    { name: 'inmcm4.1', id: 10, description: 'Institute for Numerical Mathematics', country: 'Russia' },
    { name: 'ipsl-cm5a-lr.1', id: 11, description: 'Institut Pierre-Simon Laplace', country: 'France' },
    { name: 'ipsl-cm5a-mr.1', id: 12, description: 'Institut Pierre-Simon Laplace', country: 'France' },
    { name: 'miroc5.1', id: 13, description: 'Atmosphere and Ocean Research Institute (The University of Tokyo),National Institute for Environmental Studies,and Japan Agency for Marine-Earth Science and Technology', country: 'Japan' },
    { name: 'miroc-esm.1', id: 14, description: 'Japan Agency for Marine-Earth Science and Technology,Atmosphere and Ocean Research Institute (The University of Tokyo),and National Institute for Environmental Studies', country: 'Japan' },
    { name: 'miroc-esm-chem.1', id: 15, description: 'Japan Agency for Marine-Earth Science and Technology,Atmosphere and Ocean Research Institute (The University of Tokyo),and National Institute for Environmental Studies', country: 'Japan' },
    { name: 'mpi-esm-lr.1', id: 16, description: 'Max-Planck-Institut f�r Meteorologie (Max Planck Institute for Meteorology)', country: 'Germany' },
    { name: 'mpi-esm-mr.1', id: 17, description: 'Max-Planck-Institut f�r Meteorologie (Max Planck Institute for Meteorology)', country: 'Germany' },
    { name: 'mri-cgcm3.1', id: 18, description: 'Meteorological Research Institute', country: 'Japan' },
    { name: 'noresm1-m.1', id: 19, description: 'Norwegian Climate Centre', country: 'Norway' }
];
var modelsList85 = [
    { name: 'access1-0.1', id: 20, description: 'Commonwealth Scientific and Industrial Research Organization and Bureau of Meterology,Australia', country: 'Australia' },
    { name: 'bcc-csm1-1.1', id: 21, description: 'Beijing Climate Center,China Meteorological Administration', country: 'China' },
    { name: 'canesm2.1', id: 22, description: 'Canadian Centre for Climate Modelling and Analysis', country: 'Canada' },
    { name: 'ccsm4.1', id: 23, description: 'National Center for Atmospheric Research', country: 'USA' },
    { name: 'cesm1-bgc.1', id: 24, description: 'Community Earth System Model Contributors', country: 'USA' },
    { name: 'cnrm-cm5.1', id: 25, description: 'Centre National de Recherches M�t�orologiques/Centre Europ�en de Recherche et Formation Avanc�e en Calcul Scientifique', country: 'France' },
    { name: 'csiro-mk3-6-0.1', id: 26, description: 'Commonwealth Scientific and Industrial Research Organization,Queensland Climate Change Centre of Excellence', country: 'Australia' },
    { name: 'gfdl-cm3.1', id: 27, description: 'NOAA Geophysical Fluid Dynamics Laboratory', country: 'USA' },
    { name: 'gfdl-esm2g.1', id: 28, description: 'NOAA Geophysical Fluid Dynamics Laboratory', country: 'USA' },
    { name: 'gfdl-esm2m.1', id: 29, description: 'NOAA Geophysical Fluid Dynamics Laboratory', country: 'USA' },
    { name: 'inmcm4.1', id: 30, description: 'Institute for Numerical Mathematics', country: 'Russia' },
    { name: 'ipsl-cm5a-lr.1', id: 31, description: 'Institut Pierre-Simon Laplace', country: 'France' },
    { name: 'ipsl-cm5a-mr.1', id: 32, description: 'Institut Pierre-Simon Laplace', country: 'France' },
    { name: 'miroc5.1', id: 33, description: 'Atmosphere and Ocean Research Institute (The University of Tokyo),National Institute for Environmental Studies,and Japan Agency for Marine-Earth Science and Technology', country: 'Japan' },
    { name: 'miroc-esm.1', id: 34, description: 'Japan Agency for Marine-Earth Science and Technology,Atmosphere and Ocean Research Institute (The University of Tokyo),and National Institute for Environmental Studies', country: 'Japan' },
    { name: 'miroc-esm-chem.1', id: 35, description: 'Japan Agency for Marine-Earth Science and Technology,Atmosphere and Ocean Research Institute (The University of Tokyo),and National Institute for Environmental Studies', country: 'Japan' },
    { name: 'mpi-esm-lr.1', id: 36, description: 'Max-Planck-Institut f�r Meteorologie (Max Planck Institute for Meteorology)', country: 'Germany' },
    { name: 'mpi-esm-mr.1', id: 37, description: 'Max-Planck-Institut f�r Meteorologie (Max Planck Institute for Meteorology)', country: 'Germany' },
    { name: 'mri-cgcm3.1', id: 38, description: 'Meteorological Research Institute', country: 'Japan' },
    { name: 'noresm1-m.1', id: 39, description: 'Norwegian Climate Centre', country: 'Norway' }
];

var basins = [
    { name: ' Albermarle Pamlico sounds Basin', id: 28 },
    { name: ' Apalachicola River Basin', id: 1 },
    { name: ' Arkansas White Red River Basin', id: 2 },
    { name: ' Bayou SouthFork Buffalo Basin', id: 36 },
    { name: ' BigBlack Yazo BigSunflower Basin', id: 35 },
    { name: ' Brazos River Basin', id: 3 },
    { name: ' CapeFear PeeDee Edisto Santee Basin', id: 4 },
    { name: ' Chesapeake Basin', id: 5 },
    { name: ' Colorado River Basin', id: 6 },
    { name: ' Columbia River Basin', id: 7 },
    { name: ' Coppermine Back Basin', id: 39 },
    { name: ' Delaware Basin', id: 8 },
    { name: ' Florida Ochlockonee Bay Basin', id: 9 },
    { name: ' Florida Pensacola Bay Basin', id: 10 },
    { name: ' Florida Southeast Basin', id: 11 },
    { name: ' Florida Southwest Basin', id: 12 },
    { name: ' Fraser Basin', id: 41 },
    { name: ' Great Lakes Basin', id: 33 },
    //{ name: ' Great Salt Lake', id: 13 },
    { name: ' Hudson Basin', id: 14 },
    { name: ' Kaskaskia Basin', id: 31 },
    //{ name: ' Humboldt River Basin', id: 15 },
    { name: ' Maine bay Basin', id: 16 },
    { name: ' Massachusetts bay Basin', id: 17 },
    { name: ' Meramec Basin', id: 37},
    { name: ' Missouri River Basin', id: 18 },
    { name: ' Mobile River Basin', id: 19 },
    { name: ' Obion Hatchie Basin', id: 34 },
    { name: ' Ohio River Basin', id: 20 },
    { name: ' Pearl Basin', id: 32 },
    { name: ' Red Deer Swan Basin', id: 38},
    { name: ' Rio Grande River Basin', id: 21 },
    { name: ' Sacramento Basin', id: 22 },
    { name: ' San Joaquin Basin', id: 23 },
    { name: ' Saskatchewan Basin', id: 42},
    { name: ' Satilla and Altamaha River Basin', id: 24 },
    { name: ' South Coast Alaska Basin', id: 44 },
    { name: ' Suwannee River Basin', id: 25 },
    { name: ' Thefon Dubawnt Kazan Basin', id: 40 },
    { name: ' Trinity-Neches-Sabine River Basin', id: 26 },
    { name: ' Upper Mississippi River Basin', id: 27 },
    { name: ' West Hudson Bay Basin', id: 43},
    { name: ' Yukon Basin', id: 45}

]
var modelist4527=[
    {name:'access1-0',id:'41'},
    {name:'bcc-csm1-1',id:'42'},
    {name:'bcc-csm1-1-m',id:'43'},
    {name:'bnu-esm',id:'44'},
    {name:'canesm2',id:'45'},
    {name:'ccsm4',id:'46'},
    {name:'cesm1-cam5',id:'47'},
    {name:'cnrm-cm5',id:'48'},
    {name:'csiro-mk3-6-0',id:'49'},
    {name:'fgoals-g2',id:'50'},
    {name:'gfdl-cm3',id:'51'},
    {name:'gfdl-esm2g',id:'52'},
    {name:'gfdl-esm2m',id:'53'},
    {name:'hadgem2-ao',id:'54'},
    {name:'hadgem2-cc',id:'55'},
    {name:'hadgem2-es',id:'56'},
    {name:'inmcm4',id:'57'},
    {name:'ipsl-cm5a-lr',id:'58'},
    {name:'ipsl-cm5a-mr',id:'59'},
    {name:'miroc5',id:'60'},
    {name:'miroc-esm',id:'61'},
    {name:'miroc-esm-chem',id:'62'},
    {name:'mpi-esm-lr',id:'63'},
    {name:'mpi-esm-mr',id:'64'},
    {name:'mri-cgcm3',id:'65'},
    {name:'noresm1-m',id:'66'},
    {name:'noresm1-me',id:'67'}
]

var modelist8527=[
    {name:'access1-0',id:'68'},
    {name:'bcc-csm1-1',id:'69'},
    {name:'bcc-csm1-1-m',id:'70'},
    {name:'bnu-esm',id:'71'},
    {name:'canesm2',id:'72'},
    {name:'ccsm4',id:'73'},
    {name:'cesm1-cam5',id:'74'},
    {name:'cnrm-cm5',id:'75'},
    {name:'csiro-mk3-6-0',id:'76'},
    {name:'fgoals-g2',id:'77'},
    {name:'gfdl-cm3',id:'78'},
    {name:'gfdl-esm2g',id:'79'},
    {name:'gfdl-esm2m',id:'80'},
    {name:'hadgem2-ao',id:'81'},
    {name:'hadgem2-cc',id:'82'},
    {name:'hadgem2-es',id:'83'},
    {name:'inmcm4',id:'84'},
    {name:'ipsl-cm5a-lr',id:'85'},
    {name:'ipsl-cm5a-mr',id:'86'},
    {name:'miroc5',id:'87'},
    {name:'miroc-esm',id:'88'},
    {name:'miroc-esm-chem',id:'89'},
    {name:'mpi-esm-lr',id:'90'},
    {name:'mpi-esm-mr',id:'91'},
    {name:'mri-cgcm3',id:'92'},
    {name:'noresm1-m',id:'93'},
    {name:'noresm1-me',id:'94'}
]


var modelist852=[
    {name:'gfdl-cm3',id:'95'},
    {name:'ncar-ccsm4',id:'96'},
]